name: Azure Function App CI/CD

on:
  push:
    branches: [ main ]
    paths:
    - 'rcon-function/**'
    - '!rcon-function/.gitsecret/**'
    - '!rcon-function/.vscode/**'
    - '!rcon-function/**.md'
    - '!rcon-function/.gitignore'
  pull_request:
    branches: [ main ]
    paths:
    - 'rcon-function/**'
    - '!rcon-function/.gitsecret/**'
    - '!rcon-function/.vscode/**'
    - '!rcon-function/**.md'
    - '!rcon-function/.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: rcon                         # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'rcon-function'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.111'                            # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

